eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
server:
  port: 9090
spring:
  application:
    name: gateway
zuul:
  routes:
    api:
      path: /api/**
      serviceId: eurekaprovider
