eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
server:
  port: 9765
spring:
  application:
    name: eurekaprovider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1.0
