eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9761/eureka/
server:
  port: 9766
spring:
  application:
    name: eurekaprovider
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
